### ISSUE TITLE
Some accented words as commands with Dragon do not work

### ISSUE THREAD

**Issue by comodoro** [dictation-toolbox/dragonfly#116]
When using some characters in `MappingRule` specs, they are not recognized (or rather, are recognized just with the warning below, actions are not executed). Sample script:
```
# coding: utf-8
from dragonfly import Grammar, MappingRule, Text, log


class MainRule(MappingRule):

    mapping = {
        u"D\xfcsseldorf":
            Text("Been there"),
        u"na\xefvet\xe9":
            Text("Bad trait"),
        u"naïve":
            Text("Gullible"),
        u"tête-à-tête":
            Text("Meeting")
    }

log.setup_log()

grammar = Grammar('sample')
grammar.add_rule(MainRule())
grammar.load()
```

The first one ("Düsseldorf") acts correctly, types "Been there", the others do nothing except warnings in the Natlink window:

```
engine (WARNING): Grammar sample: failed to decode recognition (u'naivet\xe9',).
engine (WARNING): Grammar sample: failed to decode recognition (u'naive',).
engine (WARNING): Grammar sample: failed to decode recognition (u'tete-a-tete',).
```

DPI 15, Windows 10, Python 2.7.16, Dragonfly current master (commit 5885b08)

**Comment by Danesprite** [comment]
Thanks for opening an issue on this. I should be able to fix this problem in the next few days.

**Comment by Danesprite** [comment]
@comodoro Sorry I took a while to get to this.

I've figured out that an encoding mismatch is causing this problem. The mappings are encoded with *utf-8* here, but the engine uses `locale.getpreferredencoding()` internally, which is typically *windows-1252* / *cp-1252* on Windows. So nothing matches when dragonfly tries to decode the recognition text to grammar rules. If you change `# coding: utf-8` to `# coding: windows-1252`, then this grammar will work correctly.

I think the way to solve this issue is to decode/encode all strings to use `locale.getpreferredencoding()` before using them for anything. This issue mostly occurs in the engine or grammar wrapper classes, so a good place to deal with it is the `EngineBase` class. I'll see what I can put together.

**Comment by comodoro** [comment]
One thing is not clear to me - what does Natlink use and what does Dragon use for encoding. Because if they are hardcoded for `windows-1252`, `getpreferredencoding()` may differ and encoding errors will just shift there. Note that Windows ANSI is not always `windows-1252`. I am on `windows-1250` and I expect many people to be on localized systems with different encodings.

**Comment by Danesprite** [comment]
It looks like natlink assumes that strings are encoded with windows-1252. That is a good point about the different encodings, it's definitely something that needs to be further addressed in dragonfly.
