### ISSUE TITLE
Commands are sometimes not recognised by Dragon NaturallySpeaking

### ISSUE THREAD

**Issue by Danesprite** [dictation-toolbox/dragonfly#138]
It has recently been brought to my attention that some commands aren't recognised properly using the natlink engine backend. This only seems to occur in very specific circumstances. The commands, even if exactly matched by Dragon, are recognised as dictation instead. This was discovered when trying the [_notepad_foodgroups.py example](https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/examples/_notepad_foodgroups.py). Some speech combinations of that grammar's rule do not work properly, such as `"I ate a hamburger yesterday"`. Commands are recognised properly if `engine.mimic()` is used.

This bug seems to be specific to more recent versions of Dragon. It occurs with Dragon 15 Home and Dragon 15 Individual, but not with Dragon 10 Preferred. Unfortunately, I don't have any other versions to test with. I can confirm that this does **not** occur with any other engine.

The bug is reproducible using Natlink grammars. Quoting words in the grammar spec fixes the issue for me (see [this natlink grammar](https://gist.github.com/Danesprite/e2b8579e8babc6afd13a73216fc3e213)), although I'm not sure why this works or what the equivalent fix in Dragonfly would be. The problem is likely solvable from Natlink. If we have to do anything in Dragonfly, it will be changing the natlink engine's [compiler class](https://github.com/dictation-toolbox/dragonfly/blob/master/dragonfly/engines/backend_natlink/compiler.py) in some way.

I've marked this issue as low-priority because I haven't seen the bug occur in any other grammar.

**Comment by quintijn** [comment]
Hi Dane, 

Andrew Zumchak brought this to my attention, and I did similar tests. In "pure Natlink" you can indeed quote words, making one word for the speech engine. Succes is certainly not guaranteed, although your experiment suggests that (quoted) 'an orange' is easier recognised than (two grammar words) 'an' 'orange'.

If you want to be as close to the speech engine possibilities, it should be wise, IMO, to have both possibilities implemented in Dragonfly too. 

BTW: Vocola only uses the quoted variant. 

In general, too many small words in grammar rules, with or without quotes tend to be recognised less easy. 

The tendency to favour commands over dictate seems to have become less prominent in recent Dragon versions, including 15. So grammars have to be designed more careful in order to have consistent recognition results of them. Which means phrase are not caught every now and then as dictate.

Probably also the quality of your sound system, especially the microphone and the absense of - electric - noise in the computer influences the consistency of recognitions.

The type of command grammar, dvc, AdvancedScript, Natlink via a "raw grammar", Vocola, Unimacro or Dragonfly or Dragonfly via another backend should not make more differences than this quoting issue, I think.

**Comment by Danesprite** [comment]
Hi Quintijn,

Thanks for "weighing in". I appreciate your insight on this issue! :-)

I agree that Dragonfly grammars should also allow quoting, especially given your observation that Dragon seems to favour dictation over commands in recent versions.

I have verified that Dragonfly's Natlink compiler also works with quoted words, so that doesn't really need changing. I did have to hackily modify Dragonfly `Literal` elements though, which obviously isn't ideal.

A new `QuotedLiteral` element class will be needed to preserve quoted words. I think this can be done with minimal modifications to engine compiler classes. The Sphinx, WSR/SAPI5 and Kaldi engines do not support quoted words. The grammar compilers for these engines should convert `QuotedLiterals` to `Literals` before using them. I'll add a `to_literal()` method to do that when I get around to implementing this.

The parser used for the `Compound`, `CompoundRule` and `MappingRule` classes should be changed to produce `QuotedLiteral` elements. Dragonfly already has a parser class for doing this, but it isn't used.

As an aside, this issue will also effect an engine using draconity instead of natlink.
@mrob95 @jcaw Just something to keep in mind. You shouldn't really need to worry about it if you use the natlink compiler class in `backend_natlink/compiler.py`.
