### ISSUE TITLE
Cannot print dictation words like `dash` in Python 2.7

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#203]
Saying Dash will produce `–`. Therefore therefore Dragonfly trying to use a keyboard symbol in the dictation element. Looks like it's an coding issue with the character.

```Python
from dragonfly import BringApp, Function, Grammar, Playback, Dictation, Choice, WaitWindow, MappingRule, Text, Key

class TestDragonfly(MappingRule):

    mapping = {

        "say <dictation>": Text("%(dictation)s"),
        }
    extras = [
        Dictation("dictation"),

    ]
    defaults = {
        "n": 1,
    }


grammar = Grammar('test dragonfly')
grammar.add_rule(TestDragonfly())
grammar.load()
```

Traceback
```
ERROR:engine.recobs:Exception during on_recognition() method of recognition observer <dragonfly.grammar.recobs_callbacks.CallbackRecognitionObserver object at 0x03F14270>: 'charmap' codec can't encode character u'\u2013' in position 12: character maps to <undefined>
Traceback (most recent call last):
  File "d:\backup\library\documents\dragonfly\dragonfly\engines\base\recobs.py", line 103, in notify_recognition
    observer.on_recognition(words, **kwargs)
  File "d:\backup\library\documents\dragonfly\dragonfly\grammar\recobs_callbacks.py", line 81, in on_recognition
    self._function(words, **kwargs)
  File "d:\backup\library\documents\dragonfly\dragonfly\__main__.py", line 74, in _on_recognition
    print("Recognized: %s" % " ".join(words))
  File "C:\Python27\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u2013' in position 12: character maps to <undefined>
```

**Comment by Danesprite** [comment]
This is happening because the [CP437 character set](https://en.wikipedia.org/wiki/Code_page_437) doesn't define the '`—`' dash character. CP437 is the character set used by your `sys.stdout` stream. The fix would be to adjust the `_on_recognition` function to encode the words before printing them:

```Python
import sys, six

def _on_recognition(words):
    message = u"Recognized: %s" % u" ".join(words)

    # This only seems to be an issue with Python 2.7 on Windows.
    if six.PY2:
        encoding = sys.stdout.encoding or "ascii"
        message = message.encode(encoding, errors='replace')
    print(message)

````

What this does is encode the words with stdout's encoding or ASCII if `sys.stdout.encoding` is `None`, as it is with Cygwin. If there are encoding errors, then those characters are replaced with question marks. The same adjustments could be made to the module loader scripts. As per my comment in the code, this problem appears to be specific to Python 2.7 on Windows. Yet another reason to stop using it.

Despite the console being unable to print the `—` character, Python still knows what it is and is able to do other things with it like type it using the `Text` action.

Incidentally, I can add the missing entries for `"dash"` and `"em-dash"` into `dictation_format.py` so the correct formatting rules are applied. I've noticed `"full-stop"` is also missing.

**Comment by LexiconCode** [comment]
Thank you for such a detailed explanation. This isn't a big issue and could go on the back burner until Python 2.7 is dropped in my opinion.

**Comment by Danesprite** [comment]
No problem. I agree that it's a minor issue. I've renamed the issue. Would the external bug tag be appropriate?
