### ISSUE TITLE
Documentation: please clarify what you mean by DNS!

### ISSUE THREAD

**Issue by cohomology** [dictation-toolbox/dragonfly#233]
As there is no product "Dragon Naturally Speaking" for a long time now, could you clarify prominently what you actually mean by this (i.e. is Dragon Home sufficient or do I need some 1000$ version of it)?

**Comment by Danesprite** [comment]
Hello @cohomology,

I will adjust the documentation to mention *Dragon* instead of *Dragon NaturallySpeaking*. The interface that Dragonfly and Natlink use for old and new versions of Dragon is very much unchanged, so it makes very little difference to us what Nuance calls it today.

As far as I know, Dragonfly and Natlink work with all editions of Dragon. They definitely work with *Dragon Home* and *Dragon Professional Individual*, so there is no need to spend $1000+. *Dragon Home* is the cheaper version. You can also buy older versions online. From memory, the recognition quality is significantly improved in versions 13 and above.

**Comment by Danesprite** [comment]
I've updated the README and other documentation files. Please let me know what you think.

**Comment by cohomology** [comment]
Thanks! Super!
