### ISSUE TITLE
Consider adding ccr support

### ISSUE THREAD

**Issue by cjbassi** [dictation-toolbox/dragonfly#240]
I saw that the documentation references some external libraries for ccr support but I was wondering if this was something that could be added to dragonfly, since it seems like something that a lot of people would want (including me :) ). Thanks.

**Comment by LexiconCode** [comment]
The following projects implement CCR and abstraction to create grammars.

[Dragonfluid](https://github.com/chajadan/dragonfluid) by chajadan (Deceased)
[Breathe](https://github.com/mrob95/Breathe) by @mrob95 
[Voca](https://github.com/python-voca/voca) by @akb 
[Osprey](https://github.com/osprey-voice/osprey) by @ cjbassi  
[Caster](https://github.com/dictation-toolbox/Caster) by synkarius and maintained by @LexiconCode 

Abstraction and CCR are two distinct issues somewhat related but for the purpose CCR will be the primary focus of this issue. Perhaps a separate issue for high-level API that compiles to dragonfly in a separate issue would be warranted.

I 100% agree that Dragonfly should have its own CCR implementation. We've missed out over many years of people coming up with thier own projects to answer that need. However I will preference that this will need a new dedicated developer to implement CCR. Most likely beyond the scope of what @Danesprite and @daanzu can provide at this time.

Put simply CCR is fairly complex. However as listed above we have people in the community that have implemented the feature and taken several different approaches. I think it's worth discussing how plan out integrating such feature into Dragonfly and working towards supporting someone to implement it. Once implemented I'm sure the community will continue to make enhancements on the future.

Here's some tangential thoughts on when thinking about CCR.

- Grammar Complexity - [Some Notes](https://explosionduck.com/wp/introduction-to-voice-programming-part-four-grammar-complexity/)
	- Optimization as 
- Conflict resolution
	- Conflicts Merging of grammars.
	- Conflicts Merging across different contexts
- Managing extra, defaults references

There are more qualified individuals to flush the sound but hopefully this gives context in the start for discussion.

**Comment by daanzu** [comment]
I don't personally use CCR, but I know that many do.

For the Kaldi backend, I think it would be almost trivial to implement an optional automatic CCR, if this is something that would be very helpful to folks.  (It is possible I am missing an important difficulty.)

The other backends are another matter, however.

**Comment by alexboche** [comment]
Don't mean to highjack this thread, but curious how much @daanzu has tried using ccr. I think ccr is a must have. I could be wrong, but I would very surprised if after a few weeks of daily use that one did not find a dramatic benefit from using ccr, no matter how complex their command set was.

**Comment by LexiconCode** [comment]
I'm willing to sponsor this issue and I would hope others would join me. I'm willing to start with $600 to have CCR implemented in dragonfly that would work with all engines as many of the projects do above.

**Comment by cjbassi** [comment]
@alexboche I asked him the same question on gitter because i was confused too and he said:

> with Kaldi, I have the response time so low that the brief pause between command chunks isn't a problem.
although I do still use some Repetitions in select places

Also to clarify, you're saying caster can only support up to 16 commands in a row?

@LexiconCode Very cool! Thanks for doing that.

On another note, this is the main issue blocking https://github.com/osprey-voice/osprey from being usable.

**Comment by LexiconCode** [comment]
> Also to clarify, you're saying caster can only support up to 16 commands in a row?

Actually Caster could support more than 16 commands in a row however it comes at the expense of grammar complexity and therefore less commands that could be made CCR. However there is potential to have optimize CCR which may lower grammar complexity. 

As a side note I have not heard of many people going over 16 commands in one utterance besides Anna.

**Comment by cjbassi** [comment]
Yeah, 16 does seem like a lot. What do you mean by 'grammar complexity' and how would that prevent comments from being added to ccr?

**Comment by LexiconCode** [comment]
> Yeah, 16 does seem like a lot. What do you mean by 'grammar complexity' and how would that prevent commands from being added to ccr?

Take a look at this [blog post](https://explosionduck.com/wp/introduction-to-voice-programming-part-four-grammar-complexity/)

**Comment by LexiconCode** [comment]
> Yeah, 16 does seem like a lot. What do you mean by 'grammar complexity' and how would that prevent commands from being added to ccr?

Take a look at this [blog post](https://explosionduck.com/wp/introduction-to-voice-programming-part-four-grammar-complexity/) as it should answer most of your questions. If I can clarify let me know.

**Comment by LexiconCode** [comment]
> Yeah, 16 does seem like a lot. What do you mean by 'grammar complexity' and how would that prevent commands from being added to ccr?

Take a look at this [blog post](https://explosionduck.com/wp/introduction-to-voice-programming-part-four-grammar-complexity/) as it should answer most of your questions. If I can clarify let me know.

**Comment by cjbassi** [comment]
Thanks, i should have read that earlier.

Question: Implementing ccr in dragonfly would be nice so that it works with all engines by default, but i'm wondering if we should actually implement it per engine if it makes more sense that way from a technical perspective, so we don't have to deal with grammar complexity and max repetitions. Modifying grammars to get ccr to work actually kind of seems like a hack to me.

**Comment by mrob95** [comment]
Breathe works well for me on both kaldi and dragon. I'm happy for it to be incorporated into dragonfly or moved into Dictation Toolbox if that would be more useful

**Comment by LexiconCode** [comment]
> so we don't have to deal with grammar complexity and max repetitions

All speech recognition engines that consume grammars have grammar complexity. I don't see why optimizations can happen both on dragonfly and on the engine to manage grammar complexity. Dragon NaturallySpeaking does not have its own implementation of CCR nor does any other commercial speech recognition engine to my knowledge that runs locally.

**Comment by LexiconCode** [comment]
> 
> 
> Breathe works well for me on both kaldi and dragon. I'm happy for it to be incorporated into dragonfly or moved into Dictation Toolbox if that would be more useful

That would be an interesting discussion to have been incorporated into Dragonfly. How does Breathe tackle some of the issues I mentioned in my the earlier post?

**Comment by cjbassi** [comment]
> All speech recognition engines that consume grammars have grammar complexity.

You're right, what i meant to say was 'so we don't have to deal with the additional grammar complexity of ccr'.

> Dragon NaturallySpeaking does not have its own implementation of CCR nor does any other commercial speech recognition engine to my knowledge that runs locally.

That's good to know. So we are definitely going to need a ccr option in dragonfly.

> For the Kaldi backend, I think it would be almost trivial to implement an optional automatic CCR, if this is something that would be very helpful to folks. (It is possible I am missing an important difficulty.)

I think it would be great if kaldiAG was able to implement ccr on its own. And then for the rest of the engines, they could just use the dragonfly ccr implementation. But of course we will have to see how things go.

**Comment by daanzu** [comment]
> I can see it being trivial to implement when you have full control over Kaldi but the point of having it in Dragonfly as an engine agnostic feature works that works for all engines now and in the future.

Certainly! I just wanted to point out that the difficulty varies greatly between different engines. Not that I want to bifurcate engine support in dragonfly.

> Question: Implementing ccr in dragonfly would be nice so that it works with all engines by default, but i'm wondering if we should actually implement it per engine if it makes more sense that way from a technical perspective, so we don't have to deal with grammar complexity and max repetitions. Modifying grammars to get ccr to work actually kind of seems like a hack to me.

Indeed, it might be best to implement it "natively" per engine, possibly with a general fallback mechanism if necessary. For instance, if my sketchy plan for implementation of CCR in Kaldi works, there should be no additional grammar complexity issues from CCR itself: it would basically come for free. And there would be no maximum number of repetitions (in fact supporting a maximum or minimum would be problematic). The result should be tremendously more efficient than currently with Caster+Kaldi.

I have poked around WSR some, and I think it similarly could have a CCR implementation that fits it better than a generic solution.

I don't know much about the current Natlink or Sphinx backends.

There would still probably be a significant amount of common code for CCR shared, likely involving the issues listed by @LexiconCode.

> Don't mean to highjack this thread, but curious how much @daanzu has tried using ccr. I think ccr is a must have. I could be wrong, but I would very surprised if after a few weeks of daily use that one did not find a dramatic benefit from using ccr, no matter how complex their command set was. To give a sense of what is possible, I note that Anna from the mathfly chat complained about the 16-command limit on ccr command sequences because she was actually hitting that constraint in her use.

True, I probably should experiment more with it. My (possibly faulty) reasons are:

* I have Kaldi tuned to have very low latency, so only the briefest of pauses is necessary between commands.
* Allowing fewer possible valid utterances increases effective accuracy.
* It gives an earlier chance to notice errors, before things spiral out of control.
* I tend to run out of breath on long commands anyway (personal issue). (A question: when you do a long CCR command chain, is it always all in one breath?)

**Comment by cjbassi** [comment]
> (A question: when you do a long CCR command chain, is it always all in one breath?)

Yeah, it is for me. It's not really something i noticed or paid attention to before though. And it seems like most of my command chains are pretty short anyway, unless it's a bunch of short ones.

**Comment by LexiconCode** [comment]
Here's the most straight forward implementation I've seen of CCR from @wolfmanstout.
http://handsfreecoding.org/2015/04/25/designing-dragonfly-grammars/

**Comment by Danesprite** [comment]
Sorry for taking a while to respond to this.

I am hesitant to add some form of built-in CCR support to Dragonfly since CCR is, as @LexiconCode pointed out, fairly complex. I cannot commit to developing or maintaining such a complex addition. It is good to know there is considerable interest though. If anyone wants to maintain something like this in Dragonfly, then it would be preferable for it to work with all SR engine backends via the `Repetition` element.

**Comment by LexiconCode** [comment]
It would be nice if this implementation had minimal abstraction that doesn't disturb the current API. Since we have direct access to dragonfly versus further layer of abstraction as demonstrated through the other projects we have an advantage. So to that end I wonder if we could do something like this.

`grammar = Grammar('sample', ccr = True)`
or
`grammar.add_rule(MainRule(), CCR = True)`

This means CCR wouldn't have its own dedicated Rule but as an rule attribute.
The entry point for the CCR to be handled would be when loading it into the engine.

From here the merging process and handling of contexts would take place.

**Comment by Danesprite** [comment]
I like this idea! It's quite similar to how CCR is specified in @mrob95's [Breathe library](https://github.com/mrob95/Breathe).

@daanzu I just wanted to mention that if you want to make Kaldi CCR optimizations, the `Repetition` element has an `optimize` parameter that could be used. It is `True` by default and was added with Dragon in mind, but can be used by any SR engine's compiler. Optimization can be disabled because there are some caveats with it. Maybe this would be helpful to you?

As a side note for others, the `optimize` parameter is largely responsible for there being far fewer "grammar too complex" errors from Dragon in recent Dragonfly versions.

**Comment by daanzu** [comment]
@Danesprite Thanks, yes, the Kaldi backend already uses the `optimize` parameter when possible, and it definitely simplifies things (although it can't if the element can be empty, which basically creates an infinite loop in the kaldi decoder).

For the Kaldi CCR optimizations, I think I can just make a CCR rule that basically just consists of RuleRefs to the other rules. I assume there is a reason this is not possible in natlink? I don't use DNS or CCR, so I could be easily missing something.

**Comment by Danesprite** [comment]
Okay then, that's good to know.

A CCR rule consisting of RuleRefs to the other rules does work properly with natlink. It is basically the right approach, it doesn't allow for referenced rules to have contexts though. I think it would be easier to implement CCR in the `Grammar` class, as mentioned above, rather than just for Kaldi.

**Comment by daanzu** [comment]
> It is basically the right approach, it doesn't allow for referenced rules to have contexts though.

You mean you just have to rebuild the CCR rule to not include the rules that are not currently in context, right?

**Comment by mrob95** [comment]
> A CCR rule consisting of RuleRefs to the other rules does work properly with natlink. It is basically the right approach, it doesn't allow for referenced rules to have contexts though. I think it would be easier to implement CCR in the `Grammar` class, as mentioned above, rather than just for Kaldi.

> You mean you just have to rebuild the CCR rule to not include the rules that are not currently in context, right?

The way it is done in Breathe is to overload the `Grammar.process_begin` method to check the context every time an utterance begins and construct a new CCR rule if necessary. This works well and avoids any of the inflexibility you get if you try and precompile all of the grammars you are ever going to need on start-up

**Comment by LexiconCode** [comment]
> 
> 
> > A CCR rule consisting of RuleRefs to the other rules does work properly with natlink. It is basically the right approach, it doesn't allow for referenced rules to have contexts though. I think it would be easier to implement CCR in the `Grammar` class, as mentioned above, rather than just for Kaldi.
> 
> > You mean you just have to rebuild the CCR rule to not include the rules that are not currently in context, right?
> 
> The way it is done in Breathe is to overload the `Grammar.process_begin` method to check the context every time an utterance begins and construct a new CCR rule if necessary. This works well and avoids any of the inflexibility you get if you try and precompile all of the grammars you are ever going to need on start-up. Obviously you would need to keep track of all of the CCR rules the user has registered and their contexts.

So the functional difference is decreased startup time and doing merger during first utterance. How does that scale with as the number of grammars increase in number and complexity?

This trade-off could be decreased by checking context on foreground window change and utilizing checking context on first utterance. That way merger takes place as soon as the window changes. Not all context are activated by changing focus so the `Grammar.process_begin`  is still needed.

**Comment by daanzu** [comment]
To confirm: with natlink, if a Rule is disabled by its context not being active, a RuleRef to that rule from another rule that is active will still work fine?

@LexiconCode Are there any features from Caster's CCR implementation that are missing in Breathe's? Or just the possible performance difference between the two approaches? How does Caster handle merging upon context changes, if not in `Grammar.process_begin` like Breathe?

**Comment by mrob95** [comment]
I don't think the scaling is a problem, merging a new grammar for a context combination that hasn't been seen before is very cheap - basically just building a list of references. With kaldi there is a noticeable (a few seconds) lag when a new grammar needs to be compiled, but once all of the grammars you use regularly have been cached by kaldi it is no longer an issue.

**Comment by mpourmpoulis** [comment]
I believe there is some overlap with Some of the issues discussed [here](https://github.com/dictation-toolbox/Caster/issues/798)

@LexiconCode In the general case, the number of combinations that can arise from CCR's is exponentially with the number of grammars With context, so computing them all in advance does not scale well. In practice, at least for the moment, I believe it is highly unlikely that the user is going to Need all of those combinations,so Caster Only combines Each context grammar only with the global grammars, Which sacrifices flexibility Because you cannot combine specs from Two context grammars in the same spoken utterance

by the way with the current implementation, the time cost for the Python code ( no idea about the backened compilation) scales linearly with the number of context grammars. On my end, I think it is around 200-250 ms per grammar depending on what I have active, though I have managed to get it if I remember correctly as high as 350-400 ms by turning on more stuff what I'm not currently using.

@daanzu Castor also preforms compatibility checking between the grammars it is going to merge, so they don't share specs( although I would like to point out that the check is not deep, in that it verifies only if specs have identical mapping keys, and not if they may be sharing a common spoken form when all extras are accounted for)

@mrob95 I think Breathe performs little bit differently than on castor, by creating and reusing `BoundCompound`, which are derived from dragonfly compounds. I lack experience with the dragonfly source code, so a small question if possible. Are those compiled individually and thenany grammar that wants to use them can simply pick up those precompiled versions, or are they compiled again every time? also don't processes like minimization add a cost every time you remerge, or am I understanding something wrong here about how kaldi works?

as a final note, frequently changing self modifying CCR's will invalidate the cache of sub_grammars Breathe maintains, but thought is either way the keys with Caster already

**Comment by mrob95** [comment]
> @mrob95 I think Breathe performs little bit differently than on castor, by creating and reusing `BoundCompound`, which are derived from dragonfly compounds. I lack experience with the dragonfly source code, so a small question if possible. Are those compiled individually and thenany grammar that wants to use them can simply pick up those precompiled versions, or are they compiled again every time? also don't processes like minimization add a cost every time you remerge, or am I understanding something wrong here about how kaldi works?

That's correct. Each command is only parsed into a `Compound` element once, and then those are reused for all grammars that need them. The merge process looks like:
* Generate a list of (references to) `Compound` elements (commands) which match the current context
* Wrap the list in an `Alternative` element
* Wrap that in a `Repetition` element
* Create the rule

Parsing is the biggest cost on the dragonfly side so there is a lot to be gained by speeding up parsing itself or minimising the number of times you parse the same thing (really there is no reason to do it more than once).

You're right that kaldi has to do a bunch of work when it encounters a new grammar, which takes a few seconds. Kaldi caches grammars it has seen before though and that persists across sessions, so you only pay that penalty once.

**Comment by LexiconCode** [comment]
There's one other feature that Caster implements during the merger and for all grammars is global spec complete / partial replacement. These have access to the entire grammar including extras / defaults. This is known as simplified transformers. This is a highly used feature in Caster.

Another feature that breathe implements is custom top level grammars which allows for greedy dictation.

There are some other features that Caster implements such as reloading grammars on save and as well as other classes like self-modifying rules and custom actions such as asynchronous action. However those can probably be reimplemented with time using whatever CCR is developed.

**Comment by Danesprite** [comment]
Is there still interest in this feature?  There haven't been any comments in well over a year.

I must say that I don't really understand the problem with using one of the libraries that have already solved the problem.  Breathe lets you define commands like mapping rules and reduces CCR to one boolean argument:

```Python
from breathe import Breathe
from dragonfly import Key, IntegerRef, Choice

# Define commands and extras.
mapping = {
    "<direction> [<n>]": Key("%(direction)s:%(n)d"),
    "delete [<n>]": Key("del:%(n)d"),
    "back [<n>]": Key("backspace:%(n)d"),
}
extras = [
    IntegerRef("n", 1, 100),
    Choice("direction", {
        "left": "left",
        "right": "right",
        "up": "up",
        "down": "down",
    }),
]

# Add global CCR commands.
Breathe.add_commands(
    context=None,
    mapping=mapping,
    extras=extras,
    ccr=True,  # Toggle for no CCR.
    top_level=True
)

```

`add_commands()` can be used to add other global or context-specific CCR (or non-CCR) commands and Breathe handles grammar merging for you.  It is nicely designed and works well.

The aforementioned idea of adding a similar `ccr` argument to the `Grammar` class is, upon reflection, ill-advised.  It wouldn't work as expected if another CCR grammar was loaded with the same context.  This is because there could be no clean grammar merging process this way.

I would be opposed to any automatic, engine-specific CCR behaviour since that would break the way grammars have always worked in Dragonfly.  It could, for instance, lead to confusion about which grammar is supposed to handle the recognition.  If the answer is "both", that would have to be implemented as a hack.

Maybe I am wrong, but I still think this is better left to other libraries that have already solved the problem.  Why reinvent the wheel?
