### ISSUE TITLE
platform context helper functions?

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/dragonfly#293]
I'm starting to do some cross platforming for Caster. There are many places where the same action just has a slightly different key combination depending on the platform. Something like `WindowsContext`, `MacOSContext`, and `LinuxContext` functions would be really helpful. I've been trying to write these based on `FuncContext` and `sys.platform == "win32"`, `sys.platform == "darwin"` and `sys.platform == "linux"` but haven't figured it out. Any help?

**Comment by kendonB** [comment]
Ok funccontext was not it. This seems to work. Is this right?

```
class LinuxContext(Context):
    def __init__(self):
        self._str = "Test for linux"
    
    def matches(self, executable, title, handle):
        return sys.platform == "linux"
```

**Comment by Danesprite** [comment]
Hi @kendonB. It's good you're working on cross-platforming Caster. You can do platform contexts with `FuncContext` like this:

```Python
import os
import sys

from dragonfly import FuncContext

windows_context = FuncContext(lambda: sys.platform == "win32")
darwin_context = FuncContext(lambda: sys.platform == "darwin")
linux_context = FuncContext(lambda: sys.platform.startswith("linux"))
x11_context = FuncContext(lambda: os.environ.get("XDG_SESSION_TYPE") == "x11")

```

As for the slightly different key combinations, this has come up before in [this discussion](https://gitter.im/dictation-toolbox/Caster?at=5f16805515e5e72fb366ca45) in the Caster gitter channel involving @amatveie, @LexiconCode and myself. Implementing an extensible way of solving this problem is quite complicated, as cross-platform support usually is. I have some notes on it, but I can't really commit to developing it myself. I'll try to put my notes up here soon.

**Comment by kendonB** [comment]
Those commands above will work fine - will close. Thanks!
