### ISSUE TITLE
ContextAction runs both the default and a context if the default action switches into that context

### ISSUE THREAD

**Issue by kendonB** [dictation-toolbox/dragonfly#301]
`example.py`
```python
from dragonfly import ContextAction, BringApp, AppContext, Key, Text, Pause

def bring_and_pause(app):
    BringApp("firefox").execute()
    Pause("300").execute()

ContextAction(default=bring_and_pause("firefox"), actions=[
                (AppContext("firefox"), Key("c-l") + Text("Hello!"))
            ]).execute()
```
Then run `python example.py`

**Comment by kendonB** [comment]
This was on Ubuntu 20.04 with the latest pip dragonfly

**Comment by Danesprite** [comment]
Thanks for opening this issue. This is not really a bug with `ContextAction`, but with your `default` argument. I'm guessing this is what you wanted to do:

```Python
from dragonfly import ContextAction, BringApp, AppContext, Key, Text, Pause, Function

def bring_and_pause(app):
    BringApp("firefox").execute()
    Pause("300").execute()

ContextAction(default=Function(lambda: bring_and_pause("firefox")), actions=[
                (AppContext("firefox"), Key("c-l") + Text("Hello!"))
            ]).execute()

```

So, `bring_and_pause()` had already run before your `ContextAction` had been initialised. You could also do something like this instead, with the same `ContextAction` part:

```Python
def bring_and_pause(app):
    return BringApp(app) + Pause("300")

```

This should be much clearer in any case. I will add some type checking into `ContextAction` so that it rejects "actions" that do not inherit from the `ActionBase` class. That way you will get an error running your original code when `bring_and_pause()` returns `None` :-)

**Comment by kendonB** [comment]
awesome! thanks so much

**Comment by kendonB** [comment]
Agree that a useful error message would be best for this case.

**Comment by Danesprite** [comment]
No worries. I will add some type checking code soon and release the changes in the next version.
