### ISSUE TITLE
Integrate eye tracking platforms

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#50]
Eye tracking technology allows bypassing of cumbersome elements of coding by voice. Perhaps the slowest element coding by voice is navigation. Navigation also requires many dictated elements to achieve the desired location on a screen. In turn this increases the probability of symptoms related to voice strain.

There are two main implementations for categories of eye tracking. Dedicated hardware which is specifically designed for eye tracking and tends to be expensive. WebCams which are ubiquitous, relatively cheap but are less performed than alternatives.

- [ ] Tobii dedicated eye tracking hardware.
[EyeXMouse](https://github.com/Versatilus/EyeXMouse) -  Requires - Windows OS, Tobii EyeX Controller and Software

- [ ] WebCam based eye tracking
Researching...

After discussing with Versatilus's EyeXMouse fork he thought dragonfly would be a better fit for integrating eye tracking. That being said though still up for discussion.

**Comment by Danesprite** [comment]
This is an interesting idea. I don't have a Tobii EyeX, so I would be unable to test that myself. I would say that there should be a standard way of interacting with the eye tracking platforms from dragonfly if this were to go ahead.

I think that it would be easier to redistribute or point to binaries from that project (and perhaps others for webcams) instead of integrating the C/C++ code somehow.

@Versatilus I'd be interested to hear your thoughts on this. Are you thinking that the functions in simple_launcher.py should be added to dragonfly as actions?

**Comment by LexiconCode** [comment]
After some internal discussion this is viewed out of scope of the dragonfly project. Dragonfly's accessibility integrations should be on an OS level, rather than device specific.
