### ISSUE TITLE
Mimic and Playback do not work for "press letter" commands

### ISSUE THREAD

**Issue by mrob95** [dictation-toolbox/dragonfly#63]
Example:
```
"test command": Mimic("press", "alpha"),
```

I believe the words are interpreted correctly by Dragon, but they are just executed as normal dictation - so you get the text "press alpha" rather than "a". Strangely, `Mimic("press", "hash")` works fine.

For reference, the reason why I want to do this is so that I can create a command to paste from the clipboard using dragon commands, allowing interaction with admin windows. I suspect that the reason this doesn't work is a security feature within Dragon to prevent exactly this, but would be interested to know if there is another explanation. Thanks.

**Comment by Danesprite** [comment]
Try using the "press a" command instead, that works for me. I would say the equivalent commands not working is probably a bug with Dragon.

[CasterUIAutomation_POC](https://github.com/chilimangoes/CasterUIAutomation_POC) is a proof of concept for the correct way of supporting Window's UI access scheme for privileged applications. I never managed to get that working though because I had some trouble building it with Visual Studio.

I just noticed that I can interact with the admin yes/no prompt when I use `Key` from Dragon. Not sure why that's working for me.

**Comment by LexiconCode** [comment]
I can confirm that `"test command": Mimic("press", "a"),` works. @Danesprite if you need help getting in touch with @chilimangoes I could try to facilitate that.

**Comment by mrob95** [comment]
Thanks @Danesprite, problem solved! Strange bug though.

**Comment by Danesprite** [comment]
@LexiconCode Thanks, but I have enough on my plate at the moment. Besides, I don't interact with Windows admin applications/prompts very often. I think the issue would be better suited to someone who does.

If anyone else is interested in tackling #11, I'd be happy to review their work.
